"""second migration.

Revision ID: 4a21793db4a8
Revises: 
Create Date: 2020-03-30 16:47:51.379582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a21793db4a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('done', sa.Boolean(), nullable=False))
    op.drop_column('todos', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('state', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('todos', 'done')
    # ### end Alembic commands ###
